.env:
  variables:
    CUDA_VERSION: "12.8.1"
    OTB_VERSION: "9.1.1"
    PYTHON_VERSION: "3.12.10"
    GIT_VERSION: "2.49.0"

.before-script-build: &before-script-build
  - |
    if [[ ! -z "$CI_BUILD_PLATFORMS" ]]; then
      export OS_ARCH=`echo $CI_BUILD_PLATFORMS | tr ' ' '\n' | \
      sed 's|\/||2' | sed 's|\/|-|' | tr '\n' ' '`
    fi
  - |
    export CI_APP_REPO=${CI_APP_REPO:-$CI_REGISTRY_IMAGE}
    if [[ $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "ltr" ]]; then
      export CI_APP_TAG=${CI_APP_TAG:-$QGIS_VERSION}
    else
      export CI_APP_TAG=${CI_APP_TAG:-$CI_COMMIT_SHA}
    fi
  - >
    echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER
    --password-stdin $CI_REGISTRY
  - >
    export VERSION_MAJ_MIN=`echo $QGIS_VERSION |
    sed -n "s|\([[:digit:]]\+\.[[:digit:]]\+\).*|\1|p"`
    
    export VERSION_MAJ=`echo $QGIS_VERSION |
    sed -n "s|\([[:digit:]]\+\).*|\1|p"`

.build:
  image: glcr.b-data.ch/docker/docker:dind
  extends: .env
  stage: build
  services:
    - name: glcr.b-data.ch/docker/docker:dind
      alias: docker
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
    BUILDX_NO_DEFAULT_ATTESTATIONS: "true"
  before_script:
    - *before-script-build
  retry: 2

.post:
  image: glcr.b-data.ch/docker/docker:dind
  stage: .post

build:latest-linux-amd64:
  extends: .build
  tags:
    - arch:amd64
    - os:linux
  script:
    - >
      cd base && docker build --pull
      --build-arg BASE_IMAGE
      --build-arg BASE_IMAGE_TAG
      --build-arg CUDA_IMAGE
      --build-arg CUDA_IMAGE_SUBTAG
      --build-arg CUDA_IMAGE_LICENSE
      --build-arg CUDA_VERSION
      --build-arg QGIS_VERSION
      --build-arg SAGA_VERSION
      --build-arg OTB_VERSION
      --build-arg PROC_SAGA_NG_VERSION
      --build-arg PYTHON_VERSION
      --build-arg GIT_VERSION
      --build-arg BUILD_START=$(date -uIseconds)
      -t $CI_APP_REPO:$CI_APP_TAG-linux-amd64
      -t $CI_APP_REPO:latest-linux-amd64
      -f Dockerfile .
    - >
      docker build
      --build-arg BUILD_ON_IMAGE=$CI_APP_REPO:$CI_APP_TAG-linux-amd64
      --build-arg BUILD_START=$(date -uIseconds)
      -t $CI_APP_REPO:$CI_APP_TAG-root-linux-amd64
      -t $CI_APP_REPO:latest-root-linux-amd64
      -f ../common/subtags/root/Dockerfile .
    - docker push -a $CI_APP_REPO
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_TRIGGERED && $CI_BUILD_PLATFORMS =~ /(linux\/amd64)/

build:latest-linux-arm64v8:
  extends: .build
  tags:
    - arch:arm64/v8
    - os:linux
  script:
    - >
      cd base && docker build --pull
      --build-arg BASE_IMAGE
      --build-arg BASE_IMAGE_TAG
      --build-arg CUDA_IMAGE
      --build-arg CUDA_IMAGE_SUBTAG
      --build-arg CUDA_IMAGE_LICENSE
      --build-arg CUDA_VERSION
      --build-arg QGIS_VERSION
      --build-arg SAGA_VERSION
      --build-arg PROC_SAGA_NG_VERSION
      --build-arg PYTHON_VERSION
      --build-arg GIT_VERSION
      --build-arg BUILD_START=$(date -uIseconds)
      -t $CI_APP_REPO:$CI_APP_TAG-linux-arm64v8
      -t $CI_APP_REPO:latest-linux-arm64v8
      -f Dockerfile .
    - >
      docker build
      --build-arg BUILD_ON_IMAGE=$CI_APP_REPO:$CI_APP_TAG-linux-arm64v8
      --build-arg BUILD_START=$(date -uIseconds)
      -t $CI_APP_REPO:$CI_APP_TAG-root-linux-arm64v8
      -t $CI_APP_REPO:latest-root-linux-arm64v8
      -f ../common/subtags/root/Dockerfile .
    - docker push -a $CI_APP_REPO
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_TRIGGERED && $CI_BUILD_PLATFORMS =~ /(linux\/arm64\/v8)/

build:ltr-linux-amd64:
  extends: .build
  tags:
    - arch:amd64
    - os:linux
  script:
    - >
      cd base && docker build --pull
      --build-arg BASE_IMAGE
      --build-arg BASE_IMAGE_TAG
      --build-arg CUDA_IMAGE
      --build-arg CUDA_IMAGE_SUBTAG
      --build-arg CUDA_IMAGE_LICENSE
      --build-arg CUDA_VERSION
      --build-arg QGIS_VERSION
      --build-arg SAGA_VERSION
      --build-arg OTB_VERSION
      --build-arg PROC_SAGA_NG_VERSION
      --build-arg PYTHON_VERSION
      --build-arg GIT_VERSION
      --build-arg BUILD_START=$(date -uIseconds)
      -t $CI_APP_REPO:$CI_APP_TAG-linux-amd64
      -t $CI_APP_REPO:ltr-linux-amd64
      -f Dockerfile .
    - >
      docker build
      --build-arg BUILD_ON_IMAGE=$CI_APP_REPO:$CI_APP_TAG-linux-amd64
      --build-arg BUILD_START=$(date -uIseconds)
      -t $CI_APP_REPO:$CI_APP_TAG-root-linux-amd64
      -t $CI_APP_REPO:ltr-root-linux-amd64
      -f ../common/subtags/root/Dockerfile .
    - docker push -a $CI_APP_REPO
  rules:
    - if: $CI_COMMIT_BRANCH == "ltr" && $CI_PIPELINE_TRIGGERED && $CI_BUILD_PLATFORMS =~ /(linux\/amd64)/

build:ltr-linux-arm64v8:
  extends: .build
  tags:
    - arch:arm64/v8
    - os:linux
  script:
    - >
      cd base && docker build --pull
      --build-arg BASE_IMAGE
      --build-arg BASE_IMAGE_TAG
      --build-arg CUDA_IMAGE
      --build-arg CUDA_IMAGE_SUBTAG
      --build-arg CUDA_IMAGE_LICENSE
      --build-arg CUDA_VERSION
      --build-arg QGIS_VERSION
      --build-arg SAGA_VERSION
      --build-arg PROC_SAGA_NG_VERSION
      --build-arg PYTHON_VERSION
      --build-arg GIT_VERSION
      --build-arg BUILD_START=$(date -uIseconds)
      -t $CI_APP_REPO:$CI_APP_TAG-linux-arm64v8
      -t $CI_APP_REPO:ltr-linux-arm64v8
      -f Dockerfile .
    - >
      docker build
      --build-arg BUILD_ON_IMAGE=$CI_APP_REPO:$CI_APP_TAG-linux-arm64v8
      --build-arg BUILD_START=$(date -uIseconds)
      -t $CI_APP_REPO:$CI_APP_TAG-root-linux-arm64v8
      -t $CI_APP_REPO:ltr-root-linux-arm64v8
      -f ../common/subtags/root/Dockerfile .
    - docker push -a $CI_APP_REPO
  rules:
    - if: $CI_COMMIT_BRANCH == "ltr" && $CI_PIPELINE_TRIGGERED && $CI_BUILD_PLATFORMS =~ /(linux\/arm64\/v8)/

build-manifest:latest-linux-multiarch:
  extends: .build
  needs: ["build:latest-linux-amd64", "build:latest-linux-arm64v8"]
  script:
    - |
      for i in $OS_ARCH; do
        export CI_MANIFEST_LIST="$CI_MANIFEST_LIST $CI_APP_REPO:$CI_APP_TAG-$i"
        export CI_MANIFEST_LIST_ROOT="$CI_MANIFEST_LIST_ROOT $CI_APP_REPO:$CI_APP_TAG-root-$i"
      done
    - |
      docker manifest create $CI_APP_REPO:$CI_APP_TAG $CI_MANIFEST_LIST
      docker manifest create $CI_APP_REPO:$CI_APP_TAG-root $CI_MANIFEST_LIST_ROOT
      if echo $OS_ARCH | grep "linux-arm64v8" >/dev/null ; then
        docker manifest annotate --variant v8 $CI_APP_REPO:$CI_APP_TAG \
          $CI_APP_REPO:$CI_APP_TAG-linux-arm64v8
        docker manifest annotate --variant v8 $CI_APP_REPO:$CI_APP_TAG-root \
          $CI_APP_REPO:$CI_APP_TAG-root-linux-arm64v8
      fi
      docker manifest push $CI_APP_REPO:$CI_APP_TAG
      docker manifest push $CI_APP_REPO:$CI_APP_TAG-root
    - |
      docker manifest create $CI_APP_REPO:$VERSION_MAJ_MIN $CI_MANIFEST_LIST
      docker manifest create $CI_APP_REPO:$VERSION_MAJ_MIN-root $CI_MANIFEST_LIST_ROOT
      if echo $OS_ARCH | grep "linux-arm64v8" >/dev/null ; then
        docker manifest annotate --variant v8 $CI_APP_REPO:$VERSION_MAJ_MIN \
          $CI_APP_REPO:$CI_APP_TAG-linux-arm64v8
        docker manifest annotate --variant v8 $CI_APP_REPO:$VERSION_MAJ_MIN-root \
          $CI_APP_REPO:$CI_APP_TAG-root-linux-arm64v8
      fi
      docker manifest push $CI_APP_REPO:$VERSION_MAJ_MIN
      docker manifest push $CI_APP_REPO:$VERSION_MAJ_MIN-root
    - |
      docker manifest create $CI_APP_REPO:$VERSION_MAJ $CI_MANIFEST_LIST
      docker manifest create $CI_APP_REPO:$VERSION_MAJ-root $CI_MANIFEST_LIST_ROOT
      if echo $OS_ARCH | grep "linux-arm64v8" >/dev/null ; then
        docker manifest annotate --variant v8 $CI_APP_REPO:$VERSION_MAJ \
          $CI_APP_REPO:$CI_APP_TAG-linux-arm64v8
        docker manifest annotate --variant v8 $CI_APP_REPO:$VERSION_MAJ-root \
          $CI_APP_REPO:$CI_APP_TAG-root-linux-arm64v8
      fi
      docker manifest push $CI_APP_REPO:$VERSION_MAJ
      docker manifest push $CI_APP_REPO:$VERSION_MAJ-root
    - |
      docker manifest create $CI_APP_REPO:latest $CI_MANIFEST_LIST
      docker manifest create $CI_APP_REPO:latest-root $CI_MANIFEST_LIST_ROOT
      if echo $OS_ARCH | grep "linux-arm64v8" >/dev/null ; then
        docker manifest annotate --variant v8 $CI_APP_REPO:latest \
          $CI_APP_REPO:$CI_APP_TAG-linux-arm64v8
        docker manifest annotate --variant v8 $CI_APP_REPO:latest-root \
          $CI_APP_REPO:$CI_APP_TAG-root-linux-arm64v8
      fi
      docker manifest push $CI_APP_REPO:latest
      docker manifest push $CI_APP_REPO:latest-root
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_TRIGGERED

build-manifest:ltr-linux-multiarch:
  extends: .build
  needs: ["build:ltr-linux-amd64", "build:ltr-linux-arm64v8"]
  script:
    - |
      for i in $OS_ARCH; do
        export CI_MANIFEST_LIST="$CI_MANIFEST_LIST $CI_APP_REPO:$CI_APP_TAG-$i"
        export CI_MANIFEST_LIST_ROOT="$CI_MANIFEST_LIST_ROOT $CI_APP_REPO:$CI_APP_TAG-root-$i"
      done
    - |
      docker manifest create $CI_APP_REPO:$CI_APP_TAG $CI_MANIFEST_LIST
      docker manifest create $CI_APP_REPO:$CI_APP_TAG-root $CI_MANIFEST_LIST_ROOT
      if echo $OS_ARCH | grep "linux-arm64v8" >/dev/null ; then
        docker manifest annotate --variant v8 $CI_APP_REPO:$CI_APP_TAG \
          $CI_APP_REPO:$CI_APP_TAG-linux-arm64v8
        docker manifest annotate --variant v8 $CI_APP_REPO:$CI_APP_TAG-root \
          $CI_APP_REPO:$CI_APP_TAG-root-linux-arm64v8
      fi
      docker manifest push $CI_APP_REPO:$CI_APP_TAG
      docker manifest push $CI_APP_REPO:$CI_APP_TAG-root
    - |
      docker manifest create $CI_APP_REPO:$VERSION_MAJ_MIN-ltr $CI_MANIFEST_LIST
      docker manifest create $CI_APP_REPO:$VERSION_MAJ_MIN-ltr-root $CI_MANIFEST_LIST_ROOT
      if echo $OS_ARCH | grep "linux-arm64v8" >/dev/null ; then
        docker manifest annotate --variant v8 $CI_APP_REPO:$VERSION_MAJ_MIN-ltr \
          $CI_APP_REPO:$CI_APP_TAG-linux-arm64v8
        docker manifest annotate --variant v8 $CI_APP_REPO:$VERSION_MAJ_MIN-ltr-root \
          $CI_APP_REPO:$CI_APP_TAG-root-linux-arm64v8
      fi
      docker manifest push $CI_APP_REPO:$VERSION_MAJ_MIN-ltr
      docker manifest push $CI_APP_REPO:$VERSION_MAJ_MIN-ltr-root
    - |
      docker manifest create $CI_APP_REPO:$VERSION_MAJ-ltr $CI_MANIFEST_LIST
      docker manifest create $CI_APP_REPO:$VERSION_MAJ-ltr-root $CI_MANIFEST_LIST_ROOT
      if echo $OS_ARCH | grep "linux-arm64v8" >/dev/null ; then
        docker manifest annotate --variant v8 $CI_APP_REPO:$VERSION_MAJ-ltr \
          $CI_APP_REPO:$CI_APP_TAG-linux-arm64v8
        docker manifest annotate --variant v8 $CI_APP_REPO:$VERSION_MAJ-ltr-root \
          $CI_APP_REPO:$CI_APP_TAG-root-linux-arm64v8
      fi
      docker manifest push $CI_APP_REPO:$VERSION_MAJ-ltr
      docker manifest push $CI_APP_REPO:$VERSION_MAJ-ltr-root
    - |
      docker manifest create $CI_APP_REPO:ltr $CI_MANIFEST_LIST
      docker manifest create $CI_APP_REPO:ltr-root $CI_MANIFEST_LIST_ROOT
      if echo $OS_ARCH | grep "linux-arm64v8" >/dev/null ; then
        docker manifest annotate --variant v8 $CI_APP_REPO:ltr \
          $CI_APP_REPO:$CI_APP_TAG-linux-arm64v8
        docker manifest annotate --variant v8 $CI_APP_REPO:ltr-root \
          $CI_APP_REPO:$CI_APP_TAG-root-linux-arm64v8
      fi
      docker manifest push $CI_APP_REPO:ltr
      docker manifest push $CI_APP_REPO:ltr-root
  rules:
    - if: $CI_COMMIT_BRANCH == "ltr" && $CI_PIPELINE_TRIGGERED
